# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import phenotypePredictionApp.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bin',
            fields=[
                ('bin_name', models.TextField()),
                ('md5sum', models.TextField(primary_key=True, serialize=False)),
                ('errors', models.TextField()),
                ('comple', models.FloatField()),
                ('conta', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='enog',
            fields=[
                ('enog_name', models.TextField(primary_key=True, serialize=False)),
                ('enog_descr', models.TextField()),
                ('enog_category', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.TextField()),
                ('version_nr', models.IntegerField()),
                ('is_newest', models.BooleanField()),
                ('model_desc', models.TextField()),
                ('model_train_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='model_enog_ranks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_rank', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='result_enog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='result_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.BooleanField()),
                ('accuracy', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('key', models.TextField(default=uuid.UUID('824af112-a38a-43d8-9b64-4ab270f7aa7b'), primary_key=True, serialize=False)),
                ('filename', models.TextField()),
                ('fileInput', models.FileField(upload_to=phenotypePredictionApp.models.upload_function_upload)),
                ('fileOutput', models.FileField(upload_to=phenotypePredictionApp.models.upload_function_results)),
                ('user_ip', models.TextField()),
                ('user_email', models.TextField()),
                ('job_date', models.DateTimeField(auto_now=True)),
                ('folder_path', models.TextField()),
                ('job_status', models.TextField()),
            ],
        ),
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['key'], name='phenotypePr_key_5463ae_idx'),
        ),
        migrations.AddField(
            model_name='result_model',
            name='bin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phenotypePredictionApp.bin'),
        ),
        migrations.AddField(
            model_name='result_model',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phenotypePredictionApp.model'),
        ),
        migrations.AddField(
            model_name='result_enog',
            name='bin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phenotypePredictionApp.bin'),
        ),
        migrations.AddField(
            model_name='result_enog',
            name='enog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phenotypePredictionApp.enog'),
        ),
        migrations.AddField(
            model_name='model_enog_ranks',
            name='enog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phenotypePredictionApp.enog'),
        ),
        migrations.AddField(
            model_name='model_enog_ranks',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phenotypePredictionApp.model'),
        ),
        migrations.AddIndex(
            model_name='model',
            index=models.Index(fields=['model_name', 'is_newest'], name='phenotypePr_model_n_182a57_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='model',
            unique_together=set([('model_name', 'version_nr')]),
        ),
        migrations.AddIndex(
            model_name='enog',
            index=models.Index(fields=['enog_name'], name='phenotypePr_enog_na_a75d73_idx'),
        ),
        migrations.AddField(
            model_name='bin',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phenotypePredictionApp.UploadedFile'),
        ),
        migrations.AddIndex(
            model_name='result_model',
            index=models.Index(fields=['bin', 'model'], name='phenotypePr_bin_id_422581_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='result_model',
            unique_together=set([('bin', 'model')]),
        ),
        migrations.AddIndex(
            model_name='result_enog',
            index=models.Index(fields=['enog', 'bin'], name='phenotypePr_enog_id_0f1063_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='result_enog',
            unique_together=set([('bin', 'enog')]),
        ),
        migrations.AddIndex(
            model_name='model_enog_ranks',
            index=models.Index(fields=['model', 'enog'], name='phenotypePr_model_i_85ef6b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='model_enog_ranks',
            unique_together=set([('model', 'enog', 'internal_rank')]),
        ),
        migrations.AddIndex(
            model_name='bin',
            index=models.Index(fields=['md5sum'], name='phenotypePr_md5sum_0ceaa4_idx'),
        ),
    ]
