# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import phenotypePredictionApp.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bin',
            fields=[
                ('bin_id', models.TextField()),
                ('file_name', models.TextField()),
                ('file_input', models.FileField(upload_to=phenotypePredictionApp.models.upload_function)),
                ('genome_path', models.TextField()),
                ('md5sum', models.TextField(primary_key=True, serialize=False)),
                ('errors', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='enog',
            fields=[
                ('enog_id', models.TextField(primary_key=True, serialize=False)),
                ('enog_descr', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='job',
            fields=[
                ('job_id', models.TextField(default=uuid.UUID('356d6cf2-99fa-4362-bd24-2a6f0b8e9c75'), primary_key=True, serialize=False)),
                ('user_ip', models.TextField()),
                ('user_email', models.TextField()),
                ('job_date', models.DateTimeField(auto_now_add=True)),
                ('folder_path', models.TextField()),
                ('job_status', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='model',
            fields=[
                ('model_id', models.TextField(primary_key=True, serialize=False)),
                ('model_desc', models.TextField()),
                ('model_train_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='model_enog_ranks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_rank', models.IntegerField()),
                ('enog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phenotypePredictionApp.enog')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phenotypePredictionApp.model')),
            ],
        ),
        migrations.CreateModel(
            name='result_enog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phenotypePredictionApp.bin')),
                ('enog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phenotypePredictionApp.enog')),
            ],
        ),
        migrations.CreateModel(
            name='result_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.BooleanField()),
                ('accuracy', models.FloatField()),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phenotypePredictionApp.bin')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phenotypePredictionApp.model')),
            ],
        ),
        migrations.CreateModel(
            name='ResultFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to="resultFiles/<class 'django.db.models.fields.TextField'>/")),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(default=uuid.UUID('c5abf6b0-b205-4a0b-a15d-92f06d7c16a7'))),
                ('filename', models.TextField()),
                ('file_input', models.FileField(upload_to=phenotypePredictionApp.models.upload_function)),
                ('job_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='bin',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phenotypePredictionApp.job'),
        ),
        migrations.AlterUniqueTogether(
            name='result_model',
            unique_together=set([('bin', 'model')]),
        ),
        migrations.AlterUniqueTogether(
            name='result_enog',
            unique_together=set([('bin', 'enog')]),
        ),
        migrations.AlterUniqueTogether(
            name='model_enog_ranks',
            unique_together=set([('model', 'enog', 'internal_rank')]),
        ),
    ]
