# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import phenotypePredictionApp.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(default=uuid.UUID('42aae907-588e-4745-a27f-85aba2ff17b2'))),
                ('filename', models.TextField()),
                ('fileInput', models.FileField(upload_to=phenotypePredictionApp.models.upload_function_upload)),
                ('fileOutput', models.FileField(upload_to=phenotypePredictionApp.models.upload_function_results)),
                ('user_ip', models.TextField()),
                ('user_email', models.TextField()),
                ('job_date', models.DateTimeField(auto_now=True)),
                ('folder_path', models.TextField()),
                ('job_status', models.TextField()),
            ],
        ),
    ]
