# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('phenotypePredictionApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.TextField(default=uuid.UUID('e5199b60-e1b3-4e71-9922-480b0cf4ddee'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='key',
            field=models.TextField(default=uuid.UUID('55c54353-ed0c-414b-bb67-c9d97cff9c42')),
        ),
    ]
