# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('phenotypePredictionApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.TextField(default=uuid.UUID('6bf461db-34ed-41ed-8bf1-b1ec917af007'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='key',
            field=models.TextField(default=uuid.UUID('19f20113-e612-4b02-a877-542b6ffa1f6b')),
        ),
    ]
