# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phenotypePredictionApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='document',
            new_name='fileInput',
        ),
    ]
