# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('phenotypePredictionApp', '0002_auto_20171108_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='version_nr',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='job_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.TextField(default=uuid.UUID('c9f12d62-414e-4f06-ba77-a55b6c5320ab'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='model',
            name='model_train_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='key',
            field=models.TextField(default=uuid.UUID('1add30e9-4b80-44a9-b048-0375a7079058')),
        ),
    ]
