# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('phenotypePredictionApp', '0002_auto_20171105_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='fileInput',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='docfile',
            field=models.FileField(default=django.utils.timezone.now, upload_to='documents/'),
            preserve_default=False,
        ),
    ]
