# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('phenotypePredictionApp', '0002_auto_20171121_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_name',
            field=models.TextField(default=uuid.UUID('c4e12f9f-7464-4afd-aee0-d8155b525f5e'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='key',
            field=models.TextField(default=uuid.UUID('df481050-b916-4d6b-8769-05af71f239db')),
        ),
    ]
