# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('phenotypePredictionApp', '0002_auto_20171116_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.TextField(default=uuid.UUID('d4f19f07-9171-42d5-9fe5-74ab6bbc730c'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='key',
            field=models.TextField(default=uuid.UUID('59c63d99-21ab-4278-ad1b-0df14e495417')),
        ),
    ]
