# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phenotypePredictionApp', '0003_auto_20171105_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='docfile',
            new_name='fileInput',
        ),
    ]
