# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('phenotypePredictionApp', '0003_auto_20171116_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.TextField(default=uuid.UUID('e18ba24a-b24f-477b-8b9e-3a3c1eb53dfc'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='model',
            name='mname_vnr',
            field=models.TextField(default=uuid.UUID('5b6e5830-3079-4b05-bb7e-ab5315c3457f')),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='key',
            field=models.TextField(default=uuid.UUID('693e5569-dd5d-4dbf-bda6-d876cc14677f')),
        ),
    ]
