# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('phenotypePredictionApp', '0003_auto_20171108_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.TextField(default=uuid.UUID('56a70972-3fbd-4db3-b572-0de61024d694'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='key',
            field=models.TextField(default=uuid.UUID('b62fe544-cc81-4058-8a5e-d239cf56fa15')),
        ),
    ]
