# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('phenotypePredictionApp', '0004_auto_20171116_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='id',
        ),
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.TextField(default=uuid.UUID('8c3cb7af-7c9f-46c2-8bfc-aa4fe074b34c'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='model',
            name='mname_vnr',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='key',
            field=models.TextField(default=uuid.UUID('f5b80e4e-b46b-4998-af87-97d9ea53c794')),
        ),
    ]
