# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('phenotypePredictionApp', '0004_auto_20171105_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='key',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
