# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('phenotypePredictionApp', '0004_auto_20171108_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.TextField(default=uuid.UUID('ad281638-f060-471a-bbe8-884e602f29f6'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='key',
            field=models.TextField(default=uuid.UUID('a55bea78-cc49-4778-9567-05f103bae0d5')),
        ),
    ]
