# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phenotypePredictionApp', '0005_uploadedfile_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='fileInput',
            field=models.FileField(upload_to='documents/<django.db.models.fields.TextField>'),
        ),
    ]
