# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phenotypePredictionApp', '0006_auto_20171105_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='fileInput',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
