# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import phenotypePredictionApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('phenotypePredictionApp', '0007_auto_20171105_2304'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ID',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='fileInput',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='id',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='file_input',
            field=models.FileField(default=django.utils.timezone.now, upload_to=phenotypePredictionApp.models.upload_function),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='filename',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='job_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='key',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
