# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('phenotypePredictionApp', '0008_auto_20171107_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='key',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='id',
            field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
