# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('phenotypePredictionApp', '0009_auto_20171107_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='id',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='key',
            field=models.TextField(default=uuid.UUID('7aa6e6ff-cf0d-4b1c-8c43-d27aedf2815a'), primary_key=True, serialize=False),
        ),
    ]
