# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('phenotypePredictionApp', '0010_auto_20171107_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='id',
            field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='key',
            field=models.TextField(default=uuid.UUID('448461f4-dbef-4fe8-b5a4-f26cb18f57a1')),
        ),
    ]
